{% set version = "1.1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bib2df
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bib2df_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bib2df/bib2df_{{ version }}.tar.gz
  sha256: 21b36bc9e9e1aeac5d7b47e796ca2a8f3424bfe6121d81740d3b8f8ea434fdf0

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-httr
    - r-humaniformat
    - r-stringr
  run:
    - r-base
    - r-dplyr
    - r-httr
    - r-humaniformat
    - r-stringr

test:
  commands:
    - $R -e "library('bib2df')"           # [not win]
    - "\"%R%\" -e \"library('bib2df')\""  # [win]

about:
  home: https://github.com/ropensci/bib2df
  license: GPL-3.0-only
  summary: Parse a BibTeX file to a data.frame to make it accessible for further analysis and visualization.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
